# Generated by Django 5.0.2 on 2024-02-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_person_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.TextField()),
                ('fam', models.TextField()),
                ('yosh', models.IntegerField()),
                ('yonalish', models.TextField()),
                ('kurs', models.IntegerField()),
            ],
        ),
    ]
