# Generated by Django 5.0.2 on 2024-02-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='kurs',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='yosh',
            field=models.TextField(),
        ),
    ]
